#include <stdio.h>
#define MANUAL_PAGES 1
#define PROGRAM_NAME "mgrep"
#ifndef MANUAL_MAIN_PAGE
#define MANUAL_FIRST_PAGE_TITLE "mgrep utility"
#endif
/*
    THERE WILL BE IMPLEMENTED GUIDE OF USING MGREP
    PROBABLY THIS MANUAL PAGE WILL BE NOT NEEDED i.e. THIS IS MEANING YOU KNOW UNIX GREP  
*/